version: '3.5'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
        - HOST=mongo
    ports:
      - 27017:27017
    command: mongod
    volumes:
      - ./data:/data/db
  nutrition:
    image: node-app
    container_name: nutrition
    ports:
      - '3000:3000'
    command: npm start
    environment:
      - NODE_ENV=dev
    volumes:
      - ./src:/usr/src/app/src
    restart: always